### ISSUE TITLE
appengine: stuck on 'working' after creation

### ISSUE THREAD

**Issue by ghost** [hatstand/gacertsbot#1]
everything seemed to work fine, clicked the add/request/create button (forget the wording) on the status page for both www and bare domain. both are just sitting at a status of working with the animation.

I'm going to remove the service and try once more from scratch, I will report back or close this accordingly.

edit: not sure how to do that atm, any ideas on what wrong with the existing service? anywhere to look for clues, more information you need?

**Comment by hatstand** [comment]
You might find some clues in the appengine logs.

**Comment by ghost** [comment]
ok, I'm not paying attention. I'm sorry. I had a typo in my dispatch route. Any suggestion how to reinitiate the setup? like when you first go to status.

**Comment by ghost** [comment]
I noticed there are a lot of files in the staging.project.appspot.com bucket and none in the project.appspot.com, is that normal?

**Comment by hatstand** [comment]
I think you'd have to manually remove the datastore entities right now.

**Comment by hatstand** [comment]
I'm not sure what you mean about the buckets?

**Comment by ghost** [comment]
Oh wow, I can't believe I didn't think to clear out the tables. Thank you so much for being tech support. Everything is working now.
